name: build

on: [push, pull_request]

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Pip cache
        uses: actions/cache@v2
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/pyproject.toml') }}
      - name: Upgrade Pip
        run: python -m pip install -U pip
      - name: Install this package
        run: python -m pip install .
      - name: Run tests
        run: python -m unittest discover pelican/plugins/md_math
